// Generated by website/scripts/generate-api-sidebars.js - do not edit manually
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

export const apiSidebarItems: SidebarsConfig['docsSidebar'] = [
  {
    "type": "category",
    "label": "Python API",
    "collapsed": false,
    "link": {
      "type": "doc",
      "id": "api/python/index"
    },
    "items": [
      "api/python/qumat",
      "api/python/qumat.qdp"
    ]
  },
  {
    "type": "category",
    "label": "Rust API",
    "collapsed": false,
    "link": {
      "type": "doc",
      "id": "api/rust/qdp-core"
    },
    "items": [
      "api/rust/qdp-core"
    ]
  }
];
